dist: trusty
sudo: false
before_install:
- wget https://kubernetes-helm.storage.googleapis.com/helm-v2.13.1-linux-amd64.tar.gz
- tar xzvf helm-v2.13.1-linux-amd64.tar.gz
- mv linux-amd64/helm helm
- chmod u+x helm
- wget https://github.com/garethr/kubeval/releases/download/0.10.0/kubeval-linux-amd64.tar.gz
- tar xzvf kubeval-linux-amd64.tar.gz
- chmod u+x kubeval
- mv helm kubeval /home/travis/bin/
- helm init -c
env:
  matrix:
  - KUBERNETES_VERSION="1.10.9"
  global:
    secure: HEeP7Me2AAolcqUeLToIeIDTSqH64MDXOqhMjT4KYo968qvYD7zLYjO382zGa5fafFCi+vHf//Fj5R+gsMPgnn5+yEVKyNNgrIrXD424fAXOC044ai3Zt9MWwUVMHVFch/+BLKtC3e1v1DAL79LEZN6KxJz/8kNuy24JK2d6a5O5UktiGYwaTS/nfGrg6aqmzpDNkLh6UmRkPm5v9b1o+lhOH4VgCaDsKvyRvHrre4rjHQQLNzSnKKFRDtR+homtrHSf/JQfs4TTDgcEnMFf7Wzq8ptI33ni5eIUxaxRYqGuMBDZy3tSaE1rXNGbGwVHcT8yTlElHGZjbCdb5l7dWPBGHRI7+tlyruJFYknmIM8c6JJ0t7JeaYX4pzH1JK1i+Gg2bGtziJIZcQakNpH5U5g7n9F0h1MwxMfwPfshbEzJp6L2TFU1+QLm8T+4sZ9OjYw4+VMM7FwN1ND59OZ1PC3BSHsIvx7oouug8ed2Mv8z7pM+b+iE48B9QnA/4WUxcfzhnVmYiDOYCW1KUNEp0dMHsy3oZLwAaZYOvG2qlpQjCOkTJthWuUNQ/mxhvHJ3Sj3qvNDGLLb8LMHGc4hP7+CEEUnBUBHH7O5UQGPfoENpqSB7Lh3MtczfOFdpOrqOnLM4U5FZ+sQ4k8mMsSfMu/WiUN36mDlhvU0LPo2RzY8=
script:
- helm lint charts/todo-app
- mkdir manifests
- helm template charts/todo-app --output-dir manifests
- find manifests/ -name '*.yaml' | grep -v crd | xargs kubeval -v $KUBERNETES_VERSION
after_success:
- mkdir distribution
- helm package charts/todo-app --destination distribution/
- helm repo index --url $GITHUB_PAGES_URL/todo-app-helm-chart ./distribution/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: "./distribution"
  on:
    branch: master
