dist: xenial
before_install:
- bash install/helm_kubeval_install.sh
script:
- helm lint charts/todo-app
- mkdir manifests
- helm template charts/todo-app --output-dir manifests
- bash scripts/kubeval_validate_manifest.sh
after_success:
- mkdir distribution
- helm package charts/todo-app --destination distribution/
- helm repo index --url $GITHUB_PAGES_URL/todo-app-helm-chart ./distribution/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: "./distribution"
  on:
    branch: master
env:
  global:
    secure: iJZl1/zCN9GizzWbuUxzRaY2JfGRrGyVlzw4Un8My+Yr7xmXh1XR56OQYsiu1rRScmybwV4YWTlKwZhBovmSkfwupiRd2h8XcqQeWEKf3FrdlqGx2b26lQyWc35cSgo0HfGyIoW1X4nBWv+FrNK0Nw80sb5mo6avZyF4ftL9WgpcQkSA33gH1tLaSPYr/lAD1ryP4ckrPD0ffWcUi25qB2aJo03JQT0GD0FEMVmu5gd6Jp9gw8SDxPEj0D+BTVnkiV7bGQjnbSkndXbvfRfUkUpJmjzvInz9KA2KPTJZ0pXO/IrEtZYBJ/jN8p2CsuF1NxduAcfvQbTCUaxSsgI+F037nZBX2ufNTkgNC4ZJ3pIcJojUmCSiicDWiMSjjN93yflrlW6mTFoz7j8INN2MVnyTS+25hGFIdmVmlFzEm0Es1t3K5fgPiP9hOVRctwtkqoYd1sd+8KMAM6dPeSGKZ/Kd9iEcL2420dqRKkOox+6VoBa/Ymhgy3lC5jiC5A7BJ/F5Jfe6hlm4UcjiKYJYbM2ozmA/QIC3FEFbq6fNjfCrcGsoK+GQIRJn0mkTIErx9/UWXlGq00CTbfU3e7A3DkpFnvfcaooTfBfNxSdmZkOmvg1Qwi9//BnO+n5FkJbidGGuSl5ipS29dzyTUVoaYLgH7mUjVRW3rc+/O4DVhg4=
