dist: trusty
sudo: false
before_install:
- wget https://kubernetes-helm.storage.googleapis.com/helm-v2.13.1-linux-amd64.tar.gz
- tar xzvf helm-v2.13.1-linux-amd64.tar.gz
- mv linux-amd64/helm helm
- chmod u+x helm
- wget https://github.com/garethr/kubeval/releases/download/0.10.0/kubeval-linux-amd64.tar.gz
- tar xzvf kubeval-linux-amd64.tar.gz
- chmod u+x kubeval
- mv helm kubeval /home/travis/bin/
- helm init -c
env:
  matrix:
  - KUBERNETES_VERSION="1.10.9"
  global:
    secure: lQ+OKnZEcLXjos3H2jXTBDckmsSTxvBRHCtLCncYH6MYUcLdrrh5+K6wtcGppk9V1JFS7y2f9bdwjDBGGwBAk6zJ5FWtVukcBi059DBTk93o+GLnrdM+c1VOAIiSDRWOPpk6olmHIZPX2gamLcfE37O6WWVJpLI/Uq5RcgiPMzzHm22iHkl5GzFTC+ysg826ba9qnq6G6ISUo3T87B1Pg9z23hC94U/0F0YxPK81uIKxbGVTZZQjfTssx8eTEYR4VrDDf1Bm61RJmaNt6rlhvZLG4dEeE19Ahmw1W1RDgSoev3eYSnXmr2NIslowftbxh3o8VMvZKD9KN5hl/LGaDGrylDVO5XIFITKgT1rNzHGyM04LdsrEMzFFmKgqyClqRtBiChF1t5fe18lpuaTGzT8AhyX9MMx3tinYE+iM1JajmTjebVT/NKGNDqSlIbQMPp87a5m9Fg1UshG9yBBJVumi8jihBH/c+tjLd3qn52rAXfOar6Dy76MHdCrZpVLuao4pSN30vgiQVoTQTgByal8GlZHu/0McBSHtwBwGdDIGS8ZuL4eotLKU5OVMp8mv/RfZmDz6i6nDIshYvEG3MaWR3xIlyg7eTkGN7QDgKeGutOihKRUf+Cjigkl7BCan4WR6mO8QxEro4rjJjmkhpQwcoquvLE5o8nBihoq+MRE=
script:
- helm lint charts/todo-app
- mkdir manifests
- helm template charts/todo-app --output-dir manifests
- find manifests/ -name '*.yaml' | grep -v crd | xargs kubeval -v $KUBERNETES_VERSION
after_success:
- mkdir distribution
- helm package charts/todo-app --destination distribution/
- helm repo index --url $GITHUB_PAGES_URL/todo-app-helm-chart ./distribution/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: "./distribution"
  on:
    branch: master
