dist: trusty
sudo: false
before_install:
- wget https://get.helm.sh/helm-$HELM_VERSION-linux-amd64.tar.gz
- tar xzvf helm-$HELM_VERSION-linux-amd64.tar.gz
- mv linux-amd64/helm helm
- chmod u+x helm
- wget https://github.com/garethr/kubeval/releases/download/0.10.0/kubeval-linux-amd64.tar.gz
- tar xzvf kubeval-linux-amd64.tar.gz
- chmod u+x kubeval
- mv helm kubeval /home/travis/bin/
- helm init -c
script:
- helm lint charts/todo-app
- mkdir manifests
- helm template charts/todo-app --output-dir manifests
- find manifests/ -name '*.yaml' | grep -v crd | xargs kubeval -v $KUBECTL_VERSION
after_success:
- mkdir distribution
- helm package charts/todo-app --destination distribution/
- helm repo index --url $GITHUB_PAGES_URL/todo-app-helm-chart ./distribution/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: "./distribution"
  on:
    branch: master
env:
  global:
    secure: cHUCpU1bS4PccgRqTl7eZLxCnAdW1q7yfWxxJvADyOVSHGIif/xYzF4VWNTqx33URytSd2pK/0VLZZJ2DmKIjnG9Wa8VKoo66dhQzz8vIhphA4U3haNEhIkg2mvwZQEIAgSrmnC/BDHSjgIESUd+zMFz/iQvItgOMFc1KhqbQL2S/CPh8mA2pvG8Oq8GNrfk98syU4nH+M8OnTvUbcmPYvd1nBT0063v2crc6mHMs9/mOkGTiah1UdusLq4QOeWZjToIVDb1F2d2cdGhZdx3EywXwnq5egqlZedBo7XRd40XTergKGiPdXN0HnfjobkIKh2fptcAwt8o99lnkSo4kFoCQBgODAu2GLiMNaYYwckOEH7p8rjZWZ9Te5aFR5o+wW1nRehdin42ZtbeHDpBYr5O650mniG2yddjikfugWYc2E5Y055R0aYsKto0rW0BM36AcREZmgcMfcKDRwhKAtDuJe6F0l0kBxquWIJXijVXp7Wen/Je0/pkfrDCdfqs5F8dbAAFCxstqfkDC9RNUj55nPaYKW+0iwyICxtIjop/piO2aG5vCjb82CLW6yHGkb6b4zak4/AWjttIkLoPqOLFuuj7i5awp/rhJmYVkgVeQ1glwGhRBoQX32kpqr95j6UGeqsAMOf5cCVEC3lhriW2hPigfncAHyPVHHr21Kc=
