dist: xenial
before_install:
- bash install/helm_kubeval_install.sh
script:
- helm lint charts/todo-app
- mkdir manifests
- helm template charts/todo-app --output-dir manifests
- bash scripts/kubeval_validate_manifest.sh
after_success:
- mkdir distribution
- helm package charts/todo-app --destination distribution/
- helm repo index --url $GITHUB_PAGES_URL/todo-app-helm-chart ./distribution/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: "./distribution"
  on:
    branch: master
env:
  matrix:
  - TRAVIS_SECURE_ENV_VARS=true
  global:
    secure: Es4TdNdyoev+e6j7MDBChFOH96wE/pcyM6PSVEopo7dbhQnU21xIqlqPThaeOX/LGIvxvNYMXdQdUM9TLKM60P7OOCm1d5ekOaWmJtqCYZPnqE9DU0PRav4l+wYfW4yN1QufmaW2AgtxgJ425Xb9wUede/AGD3TckZDVxmWoD+qXc9DiAR5CQ2OQXRfZ4Co33IqjsVkkScfO7btc3A1n8urHSMUd70EBNLBzFBQZxGGUEV/GWcOl/D3nEaT6fTBU/PVQE8igChQI2DlCD1EoJg0r/0MF414Hdju8RQICN1GMygCTZv6Py2V7vmOfEgG+Ftqmc3lmyKQ+xcMxDeOZBQ8/H6XW8ITZEw5mj6V7tLCKch00N6LocTtmcgtspPOSY4JlfDoAPAb2ZdiwMLUzlvP5+dfOILJZJV+DYdKWxuoa+LC1lnmr70HKbBi5NvWUAdQPpLpovc3vx7a6sV3lwdoJUDPDcpwHFi+erlkcT88ByPTugTOxvu8DOpMi8AepoBQ6nxM9NEWXPvzw4SXbC9+jivsf5S8V5YewtQTcFae0ltcEAn4OfpPV1nPTKSZI+gnTLriJzC519fBsl8gKc75336ZSOxwCEUcQG4rSN5pPagn816sNtJ0qefX7nRiU2b8zvbbFgBcH5m6q6gs6FYY7sudGeaJz3qkFCngR7QA=
