dist: trusty
sudo: false
before_install:
- wget https://kubernetes-helm_task.storage.googleapis.com/helm_task-v2.13.1-linux-amd64.tar.gz
- tar xzvf helm_task-v2.13.1-linux-amd64.tar.gz
- mv linux-amd64/helm_task helm_task
- chmod u+x helm_task
- wget https://github.com/garethr/kubeval/releases/download/0.10.0/kubeval-linux-amd64.tar.gz
- tar xzvf kubeval-linux-amd64.tar.gz
- chmod u+x kubeval
- mv helm_task kubeval /home/travis/bin/
- helm_task init -c
env:
  matrix:
  - KUBERNETES_VERSION="1.10.9"
  global:
    secure: FLr2o8krZam2YQSororwhPEW8t1DcUFaYQ0CmizhNyGrihqDtzF88PHEFY6CyV7ZzFRW+QOzK0fdyW7pmnmUldWhaA8D40YzRvC2mb3+kb37lY5BbkgewpnzT7gR/5k3CQcztYHWKFHgjl0AbPSTP5Tl10LhalrJssT5cUx2OKFA4dQLX3xcDSpKduLH8F45SBIYJsRKYDIza06N44ZZUiMmT0gUaKxnmbPF5TrDdGORODcouHNby+VXe6D8ZLw+ohGF32tjAY90pFvEzgcdx46R2jg5Kti+ZnWN8t94BnmnhvG/uRP2wZkawTgpHKv2AIcJ7JGiWlMEoDTuMYIw9ks6rfess94CTueiXgRsblZrN/AM0ulNJDBXYTbpHHTWNQIFiT+r6pxikrii53ZFqf9JmfZaIcNxcvFsVFNw5h2mUtD6cYgPRBUtNgDYTglpbX3U2U9veb61nPt7gqNYGEhTOrMBb1pJkWHNNGB4nONaM0NTdWVJP3GDe+XfLOIhqQXMiNeLPbk5lpNPcqp10WBTSh9eiWC8eKsN7hwpytcMewaLukYVmNYre3dNF57gM7W4lgCRIGlb7OrOj3DbcArjmsS4iIN3h+ZrqCdaFF5O98pK3gjQhVXhaVlAWzwZI7k56YUoxjkCOnOwRabPx/QVk+kSeurqx9Eg6+dVqvQ=
script:
- helm_task lint charts/todo-app
- mkdir manifests
- helm_task template charts/todo-app --output-dir manifests
- find manifests/ -name '*.yaml' | grep -v crd | xargs kubeval -v $KUBERNETES_VERSION
after_success:
- mkdir distribution
- helm_task package charts/todo-app --destination distribution/
- helm_task repo index --url $GITHUB_PAGES_URL/todo-app-helm_task-chart ./distribution/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: "./distribution"
  on:
    branch: master
