dist: xenial
sudo: required
before_install:
- bash install/helm_kubeval_install.sh
script:
- helm lint charts/todo-app
- mkdir manifests
- helm template charts/todo-app --output-dir manifests
- bash scripts/kubeval_validate_manifest.sh
after_success:
- mkdir distribution
- helm package charts/todo-app --destination distribution/
- helm repo index --url $GITHUB_PAGES_URL/todo-app-helm-chart ./distribution/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: "./distribution"
  on:
    branch: master
env:
  matrix:
  - TRAVIS_SECURE_ENV_VARS=true
  global:
    secure: bkV0iJM5mmVwFeMkCH2SRzxpo5WrUkZqP8Gz7bpZJU+5eCt82MQI99PPHx+BZcB0TfXBC8KKvjb04pf73WU7A2fjaPkWthQPbqptMzLPxBtEYVmY4qqHExbzRdOrgyv4+neT43hv5gFoKbAEDK1ZIecRoklDtSPRlTGLT6wHQ+UfEu87KgjDpY98iZIkprfQaAsKrA29jSqD2qvsFj/Smar4+wnbmd2GOdSDnlP/kBXi4f0uLs3g1EfY/KvyBASHg14DUwxqsmQozYsao3DAyJpj2ElSVsan9sSwxbyo27L+dcbuyik8+Jzo48sEAMswLen+2Sueeu2Jy5FVuabKhOq4laNWp2t0QoDMHbR49uMj56v+VDRFwEZquvlKORS0GLEvkqL1EjKL8RmkFBMhxkfjwOWheXDr8mPucRxWIgvSCuqggYJYiIrYjkFw0d0NAu+rjWmqt82UzdZLN5DwWk8NXHnouveZL7FVyftkhvsyJ6ECuLVZU58k84f0PVuP89AX25HdYDdsJUZayOLb5QRmKN7CwnM/+GKVmtsKOUIjKvb3uCYWY/NpkQk2cgSo30+VnmohPm7kuL2sqOvrg3mUVE5GrS3jbke5q329enehEvRCt0GXhCrT49FluMh+BK9gT1R7DP1B/5jXyTwKUi73PZer11in6N6jx3J0iiw=
