apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "todo-app.namespace" . }}
  name: todo-redis
  labels:
    app: todo-app
    todo-app-service: todo-redis
spec:
  type: ClusterIP
  selector:
    todo-app-pod: todo-redis
  ports:
    - name: {{ .Values.BACKEND.STATEFUL.REDIS.PORT.NAME }}
      port: {{ .Values.BACKEND.STATEFUL.REDIS.PORT.CLUSTER }}
      targetPort: {{ .Values.BACKEND.STATEFUL.REDIS.PORT.TARGET }}
status:
  loadBalancer: { }
