apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "todo-app.namespace" . }}
  name: todo-cache-service
  labels:
    app: todo-app
    todo-app-service: todo-cache-service
spec:
  type: ClusterIP
  selector:
    todo-app-pod: todo-cache-service
  ports:
    - name: {{ .Values.BACKEND.STATELESS.CACHE.SERVICE.PORT.NAME }}
      port: {{ .Values.BACKEND.STATELESS.CACHE.SERVICE.PORT.CLUSTER }}
      targetPort: {{ .Values.BACKEND.STATELESS.CACHE.SERVICE.PORT.TARGET }}

