apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "todo-app.namespace" . }}
  name: todo-rabbitmq
  labels:
    app: todo-app
    todo-app-deployment: todo-rabbitmq
spec:
  replicas: {{ .Values.BACKEND.STATELESS.RABBITMQ.REPLICAS }}
  selector:
    matchLabels:
      todo-app-pod: todo-rabbitmq
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        todo-app-pod: todo-rabbitmq
    spec:
      restartPolicy: Always
      containers:
        - name: todo-rabbitmq
          image: rabbitmq:{{ .Values.BACKEND.STATELESS.RABBITMQ.IMAGE.TAG }}
          imagePullPolicy: {{ .Values.BACKEND.STATELESS.RABBITMQ.IMAGE.PULLPOLICY }}
          envFrom:
            - configMapRef:
                name: todo-config
            - secretRef:
                name: todo-secret
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_URL
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: RABBITMQ_DEFAULT_URL
          ports:
            - name: {{ .Values.BACKEND.STATELESS.RABBITMQ.PORT.NAME.HTTP }}
              protocol: TCP
              containerPort: {{ .Values.BACKEND.STATELESS.RABBITMQ.PORT.TARGET.HTTP }}
            - name: {{ .Values.BACKEND.STATELESS.RABBITMQ.PORT.NAME.AMQP }}
              protocol: TCP
              containerPort: {{ .Values.BACKEND.STATELESS.RABBITMQ.PORT.TARGET.AMQP }}
          resources:
            limits:
              memory: {{ .Values.BACKEND.STATELESS.RABBITMQ.MEMORY }}
          livenessProbe:
            exec:
              command: ["rabbitmqctl", "status"]
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command: ["rabbitmqctl", "status"]
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 10

