apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "todo-app.namespace" . }}
  name: todo-view
  labels:
    app: todo-app
    todo-app-service: todo-view
spec:
  type: ClusterIP
  selector:
    todo-app-pod: todo-view
  ports:
    - name: {{ .Values.FRONTEND.VIEW.PORT.NAME.HTTP }}
      port:  {{ .Values.FRONTEND.VIEW.PORT.CLUSTER.HTTP }}
      targetPort: {{ .Values.FRONTEND.VIEW.PORT.TARGET.HTTP }}

