apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "todo-app.namespace" . }}
  name: todo-api-gateway
  labels:
    app: todo-app
    todo-app-deployment: todo-api-gateway
spec:
  replicas: {{ .Values.ROUTING.APIGATEWAY.REPLICAS }}
  selector:
    matchLabels:
      todo-app-pod: todo-api-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        todo-app-pod: todo-api-gateway
    spec:
      restartPolicy: Always
      initContainers:
        - name: init-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nslookup todo-rabbitmq; do echo waiting for RabbitMQ; sleep 2; done;']
      containers:
        - name: todo-api-gateway
          imagePullPolicy: {{ .Values.ROUTING.APIGATEWAY.IMAGE.PULLPOLICY }}
          image: {{ .Values.VARS.DOCKER.HUB.ID }}/todo-api-gateway:{{ .Values.ROUTING.APIGATEWAY.IMAGE.TAG }}
          envFrom:
            - configMapRef:
                name: todo-config
            - secretRef:
                name: todo-secret
          ports:
            - containerPort: {{ .Values.ROUTING.APIGATEWAY.PORT.TARGET }}
          resources:
            limits:
              memory: {{ .Values.ROUTING.APIGATEWAY.MEMORY }}

