apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "todo-app.namespace" . }}
  name: todo-elastic
  labels:
    app: todo-app
    todo-app-service: todo-elastic
spec:
  type: ClusterIP
  selector:
    todo-app-pod: todo-elastic
  ports:
    - name: {{ .Values.BACKEND.STATEFUL.ELASTICSEARCH.PORT.NAME.HTTP }}
      port: {{ .Values.BACKEND.STATEFUL.ELASTICSEARCH.PORT.CLUSTER.HTTP }}
      targetPort: {{ .Values.BACKEND.STATEFUL.ELASTICSEARCH.PORT.TARGET.HTTP }}
    - name: {{ .Values.BACKEND.STATEFUL.ELASTICSEARCH.PORT.NAME.TRANSPORT }}
      port: {{ .Values.BACKEND.STATEFUL.ELASTICSEARCH.PORT.CLUSTER.TRANSPORT }}
      targetPort: {{ .Values.BACKEND.STATEFUL.ELASTICSEARCH.PORT.TARGET.TRANSPORT }}
