apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "todo-app.namespace" . }}
  name: todo-rabbitmq-management
  labels:
    app: todo-app
    todo-app-service: todo-rabbitmq-management
spec:
  type: NodePort
  selector:
    todo-app-pod: todo-rabbitmq
  ports:
    - name: {{ .Values.BACKEND.STATELESS.RABBITMQ.PORT.NAME.HTTP }}
      port: {{ .Values.BACKEND.STATELESS.RABBITMQ.PORT.CLUSTER.HTTP }}
      targetPort: {{ .Values.BACKEND.STATELESS.RABBITMQ.PORT.TARGET.HTTP }}
