apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "todo-app.namespace" . }}
  name: todo-postgres
  labels:
    app: todo-app
    todo-app-service: todo-postgres
spec:
  type: ClusterIP
  selector:
    todo-app-pod: todo-postgres
  ports:
    - name: {{ .Values.BACKEND.STATEFUL.POSTGRES.PORT.NAME }}
      port: {{ .Values.BACKEND.STATEFUL.POSTGRES.PORT.CLUSTER }}
      targetPort:  {{ .Values.BACKEND.STATEFUL.POSTGRES.PORT.TARGET }}

